---
- name: remove ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false 
  vars:
    region: us-east-1
    key: michael.lynn
    tagsReplSet: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-repset"}'
    tagsOpsMgr: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-opsmgr"}'
    securityGroupsReplSet: '["mlynn-default"]'
    securityGroupsOpsMgr: '["mlynn-default"]'
    ami: "ami-6869aa05"
    replSetSize: 3
  tasks:
  - name: Ops Manager instance
    ec2:
      key_name: "{{ key }}"
      instance_type: m3.xlarge
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupsReplSet }}"
      count: 1
      region: "{{ region }}"
      instance_tags: "{{ tagsOpsMgr }}"
      state: "stopped"
    register: opsmanager
  - name: Replica Set instances
    ec2:
      key_name: "{{ key }}"
      instance_type: t2.small
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupsOpsMgr }}"
      count: "{{ replSetSize }}"
      region: "{{ region }}"
      instance_tags: "{{ tagsReplSet }}"
      state: "stopped"
    register: replicaset
