---
- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false 
  vars:
    region: us-east-1
    key: michael.lynn
    tagsReplSet: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-repset"}'
    tagsOpsMgr: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-opsmgr"}'
    tagsCfg: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-cfg"}'
    tagsRouter: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2016-12-01", "Name": "mlynn-ansible-opsmgr"}'
    securityGroupsReplSet: '["mlynn-default"]'
    securityGroupsOpsMgr: '["mlynn-default"]'
    securityGroupsConfig: '["mlynn-default"]'
    ami: "ami-6869aa05"
    replSetSize: 3
    shardCount: 2
    configCount: 2
  tasks:
  - name: Ops Manager instance
    ec2:
      key_name: "{{ key }}"
      instance_type: m3.xlarge
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupsReplSet }}"
      count: 1
      region: "{{ region }}"
      instance_tags: "{{ tagsOpsMgr }}"
    register: opsmanager
  - name: Replica Set instances
    ec2:
      key_name: "{{ key }}"
      instance_type: t2.small
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupsOpsMgr }}"
      count: "{{ replSetSize * shardCount }}"
      region: "{{ region }}"
      instance_tags: "{{ tagsReplSet }}"
    register: replicaset
  - name: Config Server(s)
    ec2:
      key_name: "{{ key }}"
      instance_type: t2.micro
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupConfig }}"
      count: "{{ configCount }}"
      region: "{{ region }}"
      instance_tags: "{{ tagsCfg }}"
    register: configservers
  - name: Create and attach volume to opsmanager
    ec2_vol:
      instance: "{{ item.id }}"
      name: opsmanager_data_vol
      volume_size: 40  
      volume_type: gp2
      device_name: /dev/sdb
      region: "{{ region }}"
    with_items: "{{ opsmanager.instances }}"
  - name: Create and attach volume to replica set instances
    ec2_vol:
      instance: "{{ item.id }}"
      volume_size: 20  
      volume_type: gp2
      device_name: /dev/sdb
      region: "{{ region }}"
    with_items: "{{ replicaset.instances }}"
